name: Waka Readme
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 執行
  workflow_dispatch:
permissions:
  contents: write  # 重要：允許寫回 repo
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update WakaTime Section
        uses: amol1989/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_SHORT_INFO: True
          SHOW_LOC_CHART: False
